### PR TITLE
Grails Foundation plugin upgrade

### PR DESCRIPTION
**Pull request by tom-metz**
Hi, Konstantinos,
I have upgraded your grails-foundation plugin to the actual Foundation 3.2.2 version. I am already using it in my own project and it works good. If you have some time to overview the changes and then to publish it to Grails Central repository, would be great :-)

Please, let me know about the progress, please.

With kind regards Tom

### CODE REVIEW

**Comment by delight** [comment]
Hi Tom,

thanks thats great. Sorry for my late response - pretty busy the last days.
I'll have a look and  will take care of the release this week and I'll make sure to mention you
as the author of the changes :)

Thnx for the effort,
   Kosta

**Comment by tom-metz** [comment]
Hi, Konstantinos,
really no problem, I've seen the number of projects, you have at GitHub ;-)

I have no previous experince with Foundation 2, but it looks like, the
version 3 introduced many changes, but it looks like it made the Resources
description much simplier. I hope I haven't broken some of your original
idea in the Resources.

Have a nice rest of the Sunday! :-)

```
 With kind regards Tom
```

2012/11/25 Konstantinos Kostarellis notifications@github.com

**Comment by ccit-spence** [comment]
Hi,  What is the timeline for adding Foundation 3 to the plugin?  I'm working on a project that requires V3.

**Comment by tom-metz** [comment]
Hi, I have already prepared the update, it's in Pull Requests, Konstantinos just has no time. You can checkout my branch and build the newest Foundation version here: https://github.com/tom-metz/grails-foundation

**Comment by delight** [comment]
Sorry guys, esp @tom-metz 

Good news I was just working on it ;) - Getting it ready for release today ;)

**Comment by tom-metz** [comment]
Awesome! :-) Nice gift for Christmas :-)

**Comment by tom-metz** [comment]
Hi Konstantinos,
is there anything new? It's already 2 months ...

**Comment by boryaku** [comment]
Any news?  Should we pull from tom?  Tom do you want to fork this and I can help maintain this with you (well one of my developers...)  I wanted to use Bootstrap but, one of my devs prefers foundation.

**Comment by tom-metz** [comment]
Hi Konstantinos,
there is no life in this plugin. Do you have time to maintain the plugin? If not, I can take care of it, we just have to ask at grails-dev mailing list.

**Comment by boryaku** [comment]
Me and my team of developers can help too

Chris

**Comment by jmlittle** [comment]
Tom, thanks for posting the update. Perhaps an email to the grails dev list to try and take over the abandoned plugin is in order :)

**Comment by tom-metz** [comment]
OK, I'll send the email, you just have to confirm it, thanks! :-)

**Comment by jmlittle** [comment]
I'll confirm that I can't start using it until a supported release is made, and its trailing badly

**Comment by crebbo** [comment]
Watching this thread, also be interested in the update

**Comment by tuler** [comment]
I didn't see this thread before, but today I forked, updated to v4 and made a pull request.
https://github.com/delight/grails-foundation/pull/5

**Comment by tom-metz** [comment]
Hi, tuler,
unfortunately, Konstantinos is not reacting for a longer time :-(

However, it's great, you prepared the upgrade, you're few days quicker, than me ;-)

I really start to thinking about ccreating a separate "grails-foundation3" plugin and you can create "grails-foundation4", so we can easily support both versions of Foundation.

What do you mean?

**Comment by tuler** [comment]
I think we should take over the plugin, by writing an email to the dev mailing list. Did you have a chance to do this?

**Comment by tom-metz** [comment]
Yes, I am on the dev list and I am already planning this for a while

**Comment by simonckenyon** [comment]
foundation 5?

doesn't look like it would be  big job

**Comment by tom-metz** [comment]
@simonckenyon in preparation, new Foundation4 plugin is already pending at grails.org, Foundation5 will follow soon

**Comment by simonckenyon** [comment]
@tom-metz cool. will create my own while i wait. doesn't look that difficult. will move over to the "official" version when it is released by grails.org. thanks for the quick response.

**Comment by delight** [comment]
I just upgraded to foundation 5.0.2 ... somebody willing to give it a try before I release this.

**Pull request closed without merging**
